import DefaultLayout from '@/components/layouts/default/DefaultLayout';
import Head from 'next/head';
import { NextPageWithLayout } from './page';

const Home: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-3xl font-bold underline">
        Nextjs Typescript + TailwindCSS Template
      </h1>
    </>
  );
};

export default Home;

Home.getLayout = (page) => {
  return <DefaultLayout>{page}</DefaultLayout>;
};
