import DefaultLayout from '@/components/layouts/default/DefaultLayout';
import { GetServerSideProps, InferGetServerSidePropsType } from 'next';
import Image from 'next/future/image';
import Head from 'next/head';
import { NextPageWithLayout } from '../page';

const Pokemon: NextPageWithLayout = ({
  pokemon,
}: InferGetServerSidePropsType<typeof getServerSideProps>) => {
  return (
    <>
      <Head>
        <title>Nextjs - Pokedex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="grid grid-cols-4">
        <div
          key={pokemon.name}
          className="max-w-sm bg-white rounded-lg border border-gray-200 shadow-md dark:bg-gray-800 dark:border-gray-700"
        >
          <Image
            src={pokemon.image}
            alt="Picture of the Pokemon"
            width={500}
            height={500}
          />
          <div className="p-5">
            <h5 className="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">
              {pokemon.name}
            </h5>
          </div>
        </div>
      </div>
    </>
  );
};

export default Pokemon;

export const getServerSideProps: GetServerSideProps = async (context) => {
  const { id } = context.query;
  const res = await fetch(`https://pokeapi.co/api/v2/pokemon/${id}`);
  const pokemon = await res.json();
  const paddedId = ('00' + id).slice(-3);
  pokemon.image = `https://assets.pokemon.com/assets/cms2/img/pokedex/detail/${paddedId}.png`;
  return {
    props: { pokemon },
  };
};

Pokemon.getLayout = (page) => {
  return <DefaultLayout>{page}</DefaultLayout>;
};
